//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEHv2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MEHv2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _switch {
            get {
                return ResourceManager.GetStream("_switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а
        ///автентичен
        ///аз
        ///ако
        ///ала
        ///бе
        ///без
        ///беше
        ///би
        ///бивш
        ///бивша
        ///бившо
        ///бил
        ///била
        ///били
        ///било
        ///благодаря
        ///близо
        ///бъдат
        ///бъде
        ///бяха
        ///в
        ///вас
        ///ваш
        ///ваша
        ///вероятно
        ///вече
        ///взема
        ///ви
        ///вие
        ///винаги
        ///внимава
        ///време
        ///все
        ///всеки
        ///всички
        ///всичко
        ///всяка
        ///във
        ///въпреки
        ///върху
        ///г
        ///ги
        ///главен
        ///главна
        ///главно
        ///глас
        ///го
        ///година
        ///години
        ///годишен
        ///д
        ///да
        ///дали
        ///два
        ///двама
        ///двамата
        ///две
        ///двете
        ///ден
        ///днес
        ///дни
        ///до
        ///добра
        ///добре
        ///добро
        ///добър
        ///докато
        ///докога
        ///дори
        ///досега
        ///доста
        ///друг
        ///друга
        ///други
        ///е
        ///евтин
        ///едва
        ///един
        ///една
        ///еднаква        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bulgarianST {
            get {
                return ResourceManager.GetString("bulgarianST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i&apos;m^i am
        ///you&apos;re^you are
        ///i&apos;ve^i have
        ///you&apos;ve^you have
        ///he&apos;ll^he will
        ///i&apos;ll^i will
        ///she&apos;ll^she will
        ///they&apos;ll^they will
        ///they&apos;re^they are
        ///they&apos;ve^they have
        ///we&apos;re^we are
        ///we&apos;ve^we have
        ///what&apos;ll^what will
        ///what&apos;re^what are
        ///what&apos;ve^what have
        ///who&apos;ll^who will
        ///who&apos;re^who are
        ///who&apos;ve^who have
        ///you&apos;ll^you will
        ///we&apos;ll^we will
        ///can&apos;t^can not
        ///won&apos;t^will not
        ///isn&apos;t^is not
        ///aren&apos;t^are not
        ///ain&apos;t^are not
        ///don&apos;t^do not
        ///haven&apos;t^have not
        ///havn&apos;t^have not
        ///cannot^can not
        ///willnot^will not
        ///couldn&apos;t^could not
        ///havn&apos;t^ha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string conversions {
            get {
                return ResourceManager.GetString("conversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnes
        ///cz
        ///timto
        ///budes
        ///budem
        ///byli
        ///jses
        ///muj
        ///svym
        ///ta
        ///tomto
        ///tohle
        ///tuto
        ///tyto
        ///jej
        ///zda
        ///proc
        ///mate
        ///tato
        ///kam
        ///tohoto
        ///kdo
        ///kteri
        ///mi
        ///nam
        ///tom
        ///tomuto
        ///mit
        ///nic
        ///proto
        ///kterou
        ///byla
        ///toho
        ///protoze
        ///asi
        ///ho
        ///nasi
        ///napiste
        ///re
        ///coz
        ///tim
        ///takze
        ///svych
        ///jeji
        ///svymi
        ///jste
        ///aj
        ///tu
        ///tedy
        ///teto
        ///bylo
        ///kde
        ///ke
        ///prave
        ///ji
        ///nad
        ///nejsou
        ///ci
        ///pod
        ///tema
        ///mezi
        ///pres
        ///ty
        ///pak
        ///vam
        ///ani
        ///kdyz
        ///vsak
        ///ne
        ///jsem
        ///tento
        ///clanku
        ///clanky
        ///aby
        ///jsme
        ///pred
        ///pta
        ///jejich
        ///byl
        ///jeste
        ///az
        ///bez
        ///take
        ///pouze
        ///prvni
        ///vase
        ///ktera
        ///na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string czechstoplist {
            get {
                return ResourceManager.GetString("czechstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l&apos;ansiare^ansia
        ///un&apos;ansia^ansia
        ///d&apos;ansiare^ansia
        ///dall&apos;ansia^ansia
        ///ansiare^ansia
        ///l&apos;ansia^ansia
        ///un&apos;ansia^ansia
        ///anca^anche
        ///paurare^paura
        ///period*^periodo
        ///maio^mai
        ///cosare^cosa
        ///lung*^lungo
        ///mattinare^mattina
        ///domand*^domanda
        ///ragazzo^ragazzo
        ///ragazza^ragazza
        ///l&apos;esame^esame
        ///datare^data
        ///vitare^vita
        ///mammare^mamma
        ///assoluto^assolutamente
        ///l&apos;importare^importare
        ///importare^importanza
        ///orare^orale
        ///averlare^averlo
        ///all&apos;esame^esame
        ///neo^nei
        ///motivato^motivazione
        ///occhiare^occhi
        ///materiare^materia
        ///so^sapere        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_conversions_italian {
            get {
                return ResourceManager.GetString("default_conversions_italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ad^isim
        ///adama^adam
        ///adamı^adam
        ///adamın^adam
        ///adına^ad
        ///ailem^aile
        ///ailemden^aile
        ///aileme^aile
        ///ailemin^aile
        ///ailemle^aile
        ///aksam^akşam
        ///alıyoruz^almak
        ///alıyoruz^almak
        ///altında^alt
        ///anda^an
        ///anlat^anlatmak
        ///anlatalım^anlatmak
        ///anlatayım^anlatmak
        ///anlatıyor^anlatmak
        ///anlatıyor^anlatmak
        ///anlatmaya^anlatmak
        ///annem^anne
        ///arasında^ara
        ///arkadaşım^arkadaş
        ///arkadaşlarım^arkadaş
        ///arkadaşlarımdan^arkadaş
        ///arkadaşlarımın^arkadaş
        ///arkadaşlarımla^arkadaş
        ///arkamdan^arka
        ///artan^artmak
        ///artik^artık
        ///aslında^asıl
        ///atılan^at [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_conversions_turkish {
            get {
                return ResourceManager.GetString("default_conversions_turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aan
        ///aangaande
        ///aangezien
        ///achte
        ///achter
        ///achterna
        ///af
        ///afgelopen
        ///al
        ///aldaar
        ///aldus
        ///alhoewel
        ///alias
        ///alle
        ///allebei
        ///alleen
        ///alles
        ///als
        ///alsnog
        ///altijd
        ///altoos
        ///ander
        ///andere
        ///anders
        ///anderszins
        ///beetje
        ///behalve
        ///behoudens
        ///beide
        ///beiden
        ///ben
        ///beneden
        ///bent
        ///bepaald
        ///betreffende
        ///bij
        ///bijna
        ///bijv
        ///binnen
        ///binnenin
        ///blijkbaar
        ///blijken
        ///boven
        ///bovenal
        ///bovendien
        ///bovengenoemd
        ///bovenstaand
        ///bovenvermeld
        ///buiten
        ///bv
        ///daar
        ///daardoor
        ///daarheen
        ///daarin
        ///daarna
        ///daarnet
        ///daarom
        ///daarop
        ///daaruit
        ///daarvanlangs
        ///dan        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dutchST {
            get {
                return ResourceManager.GetString("dutchST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///à
        ///â
        ///abord
        ///afin
        ///ah
        ///ai
        ///aie
        ///ainsi
        ///allaient
        ///allo
        ///allô
        ///allons
        ///après
        ///assez
        ///attendu
        ///au
        ///aucun
        ///aucune
        ///aujourd
        ///aujourd&apos;hui
        ///auquel
        ///aura
        ///auront
        ///aussi
        ///autre
        ///autres
        ///aux
        ///auxquelles
        ///auxquels
        ///avaient
        ///avais
        ///avait
        ///avant
        ///avec
        ///avoir
        ///ayant
        ///b
        ///bah
        ///beaucoup
        ///bien
        ///bigre
        ///boum
        ///bravo
        ///brrr
        ///c
        ///ça
        ///car
        ///ce
        ///ceci
        ///cela
        ///celle
        ///celle-ci
        ///celle-là
        ///celles
        ///celles-ci
        ///celles-là
        ///celui
        ///celui-ci
        ///celui-là
        ///cent
        ///cependant
        ///certain
        ///certaine
        ///certaines
        ///certains
        ///certes
        ///ces
        ///cet
        ///cette
        ///ceux
        ///ceux- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frenchstoplist {
            get {
                return ResourceManager.GetString("frenchstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///ab
        ///aber
        ///aber
        ///ach
        ///acht
        ///achte
        ///achten
        ///achter
        ///achtes
        ///ag
        ///alle
        ///allein
        ///allem
        ///allen
        ///aller
        ///allerdings
        ///alles
        ///allgemeinen
        ///als
        ///als
        ///also
        ///am
        ///an
        ///andere
        ///anderen
        ///andern
        ///anders
        ///au
        ///auch
        ///auch
        ///auf
        ///aus
        ///ausser
        ///außer
        ///ausserdem
        ///außerdem
        ///b
        ///bald
        ///bei
        ///beide
        ///beiden
        ///beim
        ///beispiel
        ///bekannt
        ///bereits
        ///besonders
        ///besser
        ///besten
        ///bin
        ///bis
        ///bisher
        ///bist
        ///c
        ///d
        ///da
        ///dabei
        ///dadurch
        ///dafür
        ///dagegen
        ///daher
        ///dahin
        ///dahinter
        ///damals
        ///damit
        ///danach
        ///daneben
        ///dank
        ///dann
        ///daran
        ///darauf
        ///daraus
        ///darf
        ///darfst
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string germanstoplist {
            get {
                return ResourceManager.GetString("germanstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///abba
        ///abban
        ///abból
        ///addig
        ///ahhoz
        ///ahol
        ///akár
        ///aki
        ///akik
        ///akkor
        ///alá
        ///alád
        ///alájuk
        ///alám
        ///alánk
        ///alapján
        ///alátok
        ///alatt
        ///alatta
        ///alattad
        ///alattam
        ///alattatok
        ///alattuk
        ///alattunk
        ///alól
        ///alóla
        ///alólad
        ///alólam
        ///alólatok
        ///alóluk
        ///alólunk
        ///által
        ///általában
        ///ám
        ///amely
        ///amelybol
        ///amelyek
        ///amelyekben
        ///amelyeket
        ///amelyet
        ///amelyik
        ///amelynek
        ///ami
        ///amíg
        ///amikor
        ///amit
        ///amott
        ///annak
        ///annál
        ///arra
        ///arról
        ///át
        ///attól
        ///az
        ///azért
        ///aznap
        ///azok
        ///azokat
        ///azokba
        ///azokban
        ///azokból
        ///azokért
        ///azokhoz
        ///azokig
        ///azokká
        ///azokkal
        ///azoknak [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hungarianST {
            get {
                return ResourceManager.GetString("hungarianST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///abbastanza
        ///accidenti
        ///ad
        ///adesso
        ///affinche
        ///agli
        ///ahime
        ///ahimè
        ///ai
        ///al
        ///alcuna
        ///alcuni
        ///alcuno
        ///all
        ///alla
        ///alle
        ///allo
        ///altri
        ///altrimenti
        ///altro
        ///altrui
        ///anche
        ///ancora
        ///anni
        ///anno
        ///ansa
        ///assai
        ///attesa
        ///avanti
        ///avendo
        ///avente
        ///aver
        ///avere
        ///avete
        ///aveva
        ///avuta
        ///avute
        ///avuti
        ///avuto
        ///basta
        ///bene
        ///benissimo
        ///berlusconi
        ///brava
        ///bravo
        ///c
        ///casa
        ///caso
        ///cento
        ///certa
        ///certe
        ///certi
        ///certo
        ///che
        ///chi
        ///chicchessia
        ///chiunque
        ///ci
        ///ciascuna
        ///ciascuno
        ///cima
        ///cio
        ///ciò
        ///cioe
        ///cioè
        ///circa
        ///citta
        ///città
        ///codesta
        ///codesti
        ///code [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string italianstoplist {
            get {
                return ResourceManager.GetString("italianstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `a^a
        ///aagtappelen^aagtappel
        ///aagtappels^aagtappel
        ///aagten^aagt
        ///aaide^aai
        ///aaiden^aai
        ///aaien^aai
        ///aaiend^aai
        ///aaiende^aai
        ///aaiingen^aaiing
        ///aait^aai
        ///aaitje^aai
        ///aaitjes^aai
        ///aalbessen^aalbes
        ///aalbessestruiken^aalbessestruik
        ///aalelgers^aalelger
        ///aalfuiken^aalfuik
        ///aalgeren^aalgeer
        ///aalgladde^aalglad
        ///aalkaren^aalkaar
        ///aalkasten^aalkast
        ///aalkorven^aalkorf
        ///aalkuipen^aalkuip
        ///aalkwabben^aalkwab
        ///aalkwabben^aalkwabbe
        ///aalmoezen^aalmoes
        ///aalmoezeniers^aalmoezenier
        ///aalmoezenierskamers^aalmoezenierskamer
        ///aalpom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lemmatization_list_dutch {
            get {
                return ResourceManager.GetString("lemmatization_list_dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abades^abá
        ///abadesa^abá
        ///abadeses^abá
        ///ababayada^ababayáu
        ///ababayaes^ababayáu
        ///ababayao^ababayáu
        ///ababayaos^ababayáu
        ///abacelera^abacelerar
        ///abaceleraba^abacelerar
        ///abacelerabais^abacelerar
        ///abacelerábamos^abacelerar
        ///abacelerabeis^abacelerar
        ///abacelerábemos^abacelerar
        ///abaceleraben^abacelerar
        ///abacelerabes^abacelerar
        ///abacelerada^abacelerar
        ///abaceleraes^abacelerar
        ///abacelerái^abacelerar
        ///abaceleráis^abacelerar
        ///abaceleramos^abacelerar
        ///abaceleran^abacelerar
        ///abacelerando^abacelerar
        ///abacelerao^abacelerar
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_ast {
            get {
                return ResourceManager.GetString("manual_lemmatization_ast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to абоната^абонат
        ///абонати^абонат
        ///абонатите^абонат
        ///абонирахме^абонирам
        ///абревиатури^абревиатура
        ///абревиатурните^абревиатурен
        ///абсолютна^абсолютен
        ///абсолютната^абсолютен
        ///абсолютния^абсолютен
        ///абсолютно^абсолютен
        ///абсолютното^абсолютен
        ///абстрактни^абстрактен
        ///абстрактно^абстрактен
        ///абсурда^абсурд
        ///абсурдна^абсурден
        ///абсурдни^абсурден
        ///абсурдния^абсурден
        ///авангарда^авангард
        ///авангардни^авангарден
        ///авангардните^авангарден
        ///авангардистите^авангардист
        ///авансово^авансов
        ///авансовото^авансов
        ///авантажа^авантаж
        ///авант [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_bg {
            get {
                return ResourceManager.GetString("manual_lemmatization_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as^a
        ///àbacs^àbac
        ///abacàs^abacà
        ///abacallan^abacallanar
        ///abacallana^abacallanar
        ///abacallanà^abacallanar
        ///abacallanada^abacallanar
        ///abacallanades^abacallanar
        ///abacallanam^abacallanar
        ///abacallanant^abacallanar
        ///abacallanara^abacallanar
        ///abacallanarà^abacallanar
        ///abacallanaran^abacallanar
        ///abacallanaràs^abacallanar
        ///abacallanaré^abacallanar
        ///abacallanarem^abacallanar
        ///abacallanàrem^abacallanar
        ///abacallanaren^abacallanar
        ///abacallanares^abacallanar
        ///abacallanareu^abacallanar
        ///abacallanàreu^abacallanar
        ///abacallanar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_ca {
            get {
                return ResourceManager.GetString("manual_lemmatization_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aachenu^Aachen
        ///Aaronsona^Aaronson
        ///Aby^Aba
        ///abecedu^abeceda
        ///abecedním^abecední
        ///Abimelecha^Abimelech
        ///abonenta^abonent
        ///Abrahámu^Abrahám
        ///absencí^absence
        ///absentovala^absentovat
        ///absolutismu^absolutismus
        ///absolutistickou^absolutistický
        ///absolutního^absolutní
        ///absolutním^absolutní
        ///absolutními^absolutní
        ///absolutně^absolutno
        ///absolventi^absolvent
        ///absolventům^absolvent
        ///absurdity^absurdita
        ///nejabsurdnějších^absurdní
        ///abych^aby
        ///abychom^aby
        ///abys^aby
        ///abyste^aby
        ///Accolu^Accola
        ///achátové^achátový
        ///Achilla^Ach [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_cs {
            get {
                return ResourceManager.GetString("manual_lemmatization_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ac^a
        ///ag^a
        ///ag^â
        ///hab^ab
        ///abaci^abacws
        ///abadau^abad
        ///habadau^abad
        ///abatai^abaty
        ///aberoedd^aber
        ///haber^aber
        ///aberthau^aberth
        ///haberth^aberth
        ///abertha^aberthu
        ///aberthaf^aberthu
        ///aberthai^aberthu
        ///aberthais^aberthu
        ///aberthaist^aberthu
        ///aberthant^aberthu
        ///aberthasai^aberthu
        ///aberthasant^aberthu
        ///aberthasech^aberthu
        ///aberthasem^aberthu
        ///aberthasent^aberthu
        ///aberthasid^aberthu
        ///aberthasit^aberthu
        ///aberthasoch^aberthu
        ///aberthasom^aberthu
        ///aberthaswn^aberthu
        ///aberthech^aberthu
        ///aberthed^aberthu
        ///aberthem^aberthu
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_cy {
            get {
                return ResourceManager.GetString("manual_lemmatization_cy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As^A
        ///Aachens^Aachen
        ///Aale^Aal
        ///Aalen^Aal
        ///Aales^Aal
        ///Aals^Aal
        ///Aal^aalen
        ///Aale^aalen
        ///aalend^aalen
        ///Aalens^Aalen
        ///aalest^aalen
        ///aalet^aalen
        ///aalst^aalen
        ///aalt^aalen
        ///aalte^aalen
        ///aalten^aalen
        ///aaltest^aalen
        ///aaltet^aalen
        ///geaalt^aalen
        ///aalende^aalend
        ///aalendem^aalend
        ///aalenden^aalend
        ///aalender^aalend
        ///aalendere^aalend
        ///aalenderem^aalend
        ///aalenderen^aalend
        ///aalenderer^aalend
        ///aalenderes^aalend
        ///aalendes^aalend
        ///aalendste^aalend
        ///aalendstem^aalend
        ///aalendsten^aalend
        ///aalendster^aalend
        ///aalendstes^aalend
        ///Aal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_de {
            get {
                return ResourceManager.GetString("manual_lemmatization_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first^1
        ///tenth^10
        ///hundredth^100
        ///thousandth^1000
        ///millionth^1000000
        ///billionth^1000000000
        ///eleventh^11
        ///twelfth^12
        ///thirteenth^13
        ///fourteenth^14
        ///fifteenth^15
        ///sixteenth^16
        ///seventeenth^17
        ///eighteenth^18
        ///nineteenth^19
        ///second^2
        ///twentieth^20
        ///two-hundredth^200
        ///twenty-first^21
        ///twenty-second^22
        ///twenty-third^23
        ///twenty-fourth^24
        ///twenty-fifth^25
        ///twenty-sixth^26
        ///twenty-seventh^27
        ///twenty-eighth^28
        ///twenty-ninth^29
        ///third^3
        ///thirtieth^30
        ///three-hundredth^300
        ///thirty-first^31
        ///thirty-second^32
        ///thirty-thir [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_en {
            get {
                return ResourceManager.GetString("manual_lemmatization_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primer^1
        ///primera^1
        ///primeras^1
        ///primero^1
        ///primeros^1
        ///décima^10
        ///décimas^10
        ///décimo^10
        ///décimos^10
        ///centésima^100
        ///centésimas^100
        ///centésimo^100
        ///centésimos^100
        ///milésima^1000
        ///milésimas^1000
        ///milésimo^1000
        ///milésimos^1000
        ///diezmilésima^10000
        ///diezmilésimas^10000
        ///diezmilésimo^10000
        ///diezmilésimos^10000
        ///cienmilésima^100000
        ///cienmilésimas^100000
        ///cienmilésimo^100000
        ///cienmilésimos^100000
        ///millonésima^1000000
        ///millonésimas^1000000
        ///millonésimo^1000000
        ///millonésimos^1000000
        ///diezmillonésima^10000000
        ///diezmi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_es {
            get {
                return ResourceManager.GetString("manual_lemmatization_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aabitsast^aabits
        ///aabitsat^aabits
        ///Aacheni^Aachen
        ///Aadama^Aadam
        ///Aadamale^Aadam
        ///Aadamast^Aadam
        ///aadete^aade
        ///aated^aade
        ///aadli^aadel
        ///aadlikuga^aadlik
        ///aadlimatrikli^aadlimatrikkel
        ///aadlimehe^aadlimees
        ///aadlisoost^aadlisoo
        ///aadlisoost^aadlisugu
        ///aadressi^aadress
        ///aadressid^aadress
        ///aadressiks^aadress
        ///aadressil^aadress
        ///aadressist^aadress
        ///aadressraamatuid^aadressraamat
        ///Aadul^Aadu
        ///Aadule^Aadu
        ///Aafrikale^Aafrika
        ///Aafrikas^Aafrika
        ///Aafrikast^Aafrika
        ///Aafrikat^Aafrika
        ///aafriklase^aafriklane
        ///aafriklased^aaf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_et {
            get {
                return ResourceManager.GetString("manual_lemmatization_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيد^آ
        ///بيايي^آ
        ///آب‌ها^آب
        ///آپارتمانِ^آپارتمان
        ///بيام^آ
        ///آدرسِ^آدرس
        ///آپارتمان‌هايِ^آپارتمان
        ///آبجويِ^آبجو
        ///اواخرِ^آخر
        ///مي‌آيم^آ
        ///نيايد^آ
        ///آبِ^آب
        ///بياييم^آ
        ///بيا^آ
        ///مي‌آيد^آ
        ///آخرين^آخر
        ///آتش‌زدنِ^آتش‌زدن
        ///بياييد^آ
        ///آبي^آب
        ///آخرِ^آخر
        ///بيايد^آ
        ///آبيِ^آبي
        ///آب‌هايِ^آب
        ///اواخر^آخر
        ///بيايند^آ
        ///آچارهايي^آچار
        ///آبکيِ^آبکي
        ///آتشي^آتش
        ///آبي‌رنگِ^آبي‌رنگ
        ///بيايم^آ
        ///مي‌آيند^آ
        ///نمي‌آيد^آ
        ///آستين‌هايِ^آستين
        ///آمده^آمد
        ///آشنايي^آشنا
        ///آموخته^آموخت
        ///آگاهيِ^آگاهي
        ///آشوب‌هايِ^آشوب
        ///مي‌آمدند^آمد
        ///بياموزند^آموز
        ///آرايشگرِ^آرايشگر
        ///آدم‌ها^آدم
        ///آساي [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_fa {
            get {
                return ResourceManager.GetString("manual_lemmatization_fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e^2e
        ///e^58e
        ///e^7e
        ///a jeun^à jeun
        ///à posteriori^a posteriori
        ///à priori^a priori
        ///abaissante^abaissant
        ///abaissée^abaissé
        ///abaissées^abaissé
        ///abaissés^abaissé
        ///abaissements^abaissement
        ///abaissa^abaisser
        ///abaissai^abaisser
        ///abaissaient^abaisser
        ///abaissais^abaisser
        ///abaissait^abaisser
        ///abaissâmes^abaisser
        ///abaissant^abaisser
        ///abaissas^abaisser
        ///abaissasse^abaisser
        ///abaissassent^abaisser
        ///abaissasses^abaisser
        ///abaissassiez^abaisser
        ///abaissassions^abaisser
        ///abaissât^abaisser
        ///abaissâtes^abaisser
        ///abaisse^abaisser        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_fr {
            get {
                return ResourceManager.GetString("manual_lemmatization_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aba^ab
        ///abaí^ab
        ///b&apos;ab^ab
        ///b&apos;abaí^ab
        ///d&apos;ab^ab
        ///d&apos;aba^ab
        ///d&apos;abaí^ab
        ///hab^ab
        ///haba^ab
        ///habaí^ab
        ///m&apos;ab^ab
        ///m&apos;aba^ab
        ///m&apos;abaí^ab
        ///n-ab^ab
        ///n-aba^ab
        ///n-abaí^ab
        ///t-ab^ab
        ///abacais^abacas
        ///b&apos;abacais^abacas
        ///b&apos;abacas^abacas
        ///d&apos;abacais^abacas
        ///d&apos;abacas^abacas
        ///habacais^abacas
        ///habacas^abacas
        ///m&apos;abacais^abacas
        ///m&apos;abacas^abacas
        ///n-abacais^abacas
        ///n-abacas^abacas
        ///t-abacas^abacas
        ///abachta^abacht
        ///b&apos;abacht^abacht
        ///d&apos;abacht^abacht
        ///d&apos;abachta^abacht
        ///habacht^abacht
        ///habachta^abacht
        ///m&apos;abacht^abacht
        ///m&apos;abachta^abacht
        ///n-abach [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_ga {
            get {
                return ResourceManager.GetString("manual_lemmatization_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aba^ab
        ///abachan^ab
        ///abachan^aba
        ///abacasan^abacas
        ///abacais^abacas
        ///abachaidh^abachadh
        ///abaiche^abaich
        ///abaicheadh^abaich
        ///abaicheam^abaich
        ///abaicheamaid^abaich
        ///abaichear^abaich
        ///abaichibh^abaich
        ///abaichidh^abaich
        ///abaichinn^abaich
        ///abaichte^abaich
        ///abachadh^abaich
        ///abachaidh^abaich
        ///abaide^abaid
        ///abaidean^abaid
        ///abairte^abair
        ///abradh^abair
        ///abraibh^abair
        ///abram^abair
        ///abramaid^abair
        ///abrar^abair
        ///ràdh^abair
        ///teireadh^abair
        ///teireamaid^abair
        ///teirinn^abair
        ///their^abair
        ///theireadh^abair
        ///theireamaid^abair
        ///th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_gd {
            get {
                return ResourceManager.GetString("manual_lemmatization_gd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as^a
        ///ás^á
        ///abas^aba
        ///abáboros^abáboro
        ///abacás^abacá
        ///bacelamentos^abacelamento
        ///abacela^abacelar
        ///abacelaba^abacelar
        ///abacelabades^abacelar
        ///abacelabamos^abacelar
        ///abacelaban^abacelar
        ///abacelabas^abacelar
        ///abacelaches^abacelar
        ///abacelada^abacelar
        ///abaceladas^abacelar
        ///abacelade^abacelar
        ///abacelades^abacelar
        ///abacelado^abacelar
        ///abacelados^abacelar
        ///abacelamos^abacelar
        ///abacelan^abacelar
        ///abacelando^abacelar
        ///abacelara^abacelar
        ///abacelará^abacelar
        ///abacelarades^abacelar
        ///abacelaramos^abacelar
        ///abacelaran^ab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_gl {
            get {
                return ResourceManager.GetString("manual_lemmatization_gl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa-aaseyn^aa-aase
        ///aa^aeg
        ///aachaignee^aachaignagh
        ///aachassidyn^aachassid
        ///aacheoidee^aacheoidagh
        ///aacheoidyn^aacheoid
        ///aacheyllaghaghyn^aacheyllaghey
        ///aachianglaghyn^aachiangley
        ///aachiangleagh^aachiangle
        ///aachianglee^aachiangle
        ///aachianglein^aachiangle
        ///aachiangle-jee^aachiangle
        ///aachianglemayd^aachiangle
        ///aachiangley^aachiangle
        ///aachiangleym^aachiangle
        ///aachiangleys^aachiangle
        ///aachianglit^aachiangle
        ///aachlashtynyn^aachlashtyn
        ///aachloiaghyn^aachloie
        ///aachooinaghtynyn^aachooinaghtyn
        ///aa-choorsalyn^aa-choors [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_gv {
            get {
                return ResourceManager.GetString("manual_lemmatization_gv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaronsonnak^Aaronson
        ///Aaronsont^Aaronson
        ///abbahagyni^abbahagy
        ///abbahagyta^abbahagy
        ///abbahagyták^abbahagy
        ///abbahagytam^abbahagy
        ///abbahagytuk^abbahagy
        ///abbamaradni^abbamarad
        ///abbamaradt^abbamarad
        ///Abbáziában^Abbázia
        ///ábécére^ábécé
        ///ablaka^ablak
        ///ablakában^ablak
        ///ablakából^ablak
        ///ablakai^ablak
        ///ablakaik^ablak
        ///ablakaikkal^ablak
        ///ablakainak^ablak
        ///ablakán^ablak
        ///ablakát^ablak
        ///ablakba^ablak
        ///ablakhoz^ablak
        ///ablakkal^ablak
        ///ablakok^ablak
        ///ablakokat^ablak
        ///ablakokba^ablak
        ///ablakokkal^ablak
        ///ablakokon^ablak
        ///ablak [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_hu {
            get {
                return ResourceManager.GetString("manual_lemmatization_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abati^abate
        ///abbacchi^abbacchiare
        ///abbacchia^abbacchiare
        ///abbacchiai^abbacchiare
        ///abbacchiammo^abbacchiare
        ///abbacchiamo^abbacchiare
        ///abbacchian^abbacchiare
        ///abbacchiando^abbacchiare
        ///abbacchiano^abbacchiare
        ///abbacchiante^abbacchiare
        ///abbacchianti^abbacchiare
        ///abbacchiar^abbacchiare
        ///abbacchiaron^abbacchiare
        ///abbacchiarono^abbacchiare
        ///abbacchiasse^abbacchiare
        ///abbacchiasser^abbacchiare
        ///abbacchiassero^abbacchiare
        ///abbacchiassi^abbacchiare
        ///abbacchiassimo^abbacchiare
        ///abbacchiaste^abbacchiare
        ///abbacchiasti^a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_it {
            get {
                return ResourceManager.GetString("manual_lemmatization_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iodargírios^00
        ///aa^a
        ///aacheniana^aacheniano
        ///aachenianas^aacheniano
        ///aachenianos^aacheniano
        ///aais^aal
        ///aaleniana^aaleniano
        ///aalenianas^aaleniano
        ///aalenianos^aaleniano
        ///abas^aba
        ///abinha^aba
        ///abinhas^aba
        ///abita^aba
        ///abitas^aba
        ///ababás^ababá
        ///ababalhamentos^ababalhamento
        ///ababalha^ababalhar
        ///ababalhá^ababalhar
        ///ababalhada^ababalhar
        ///ababalhadas^ababalhar
        ///ababalhado^ababalhar
        ///ababalhados^ababalhar
        ///ababalhai^ababalhar
        ///ababalhais^ababalhar
        ///ababalham^ababalhar
        ///ababalhamo^ababalhar
        ///ababalhámo^ababalhar
        ///abab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_pt {
            get {
                return ResourceManager.GetString("manual_lemmatization_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.d.^a_dato
        ///abale^aba
        ///abalei^aba
        ///abalele^aba
        ///abalelor^aba
        ///abaua^aba
        ///abace^abac
        ///abacele^abac
        ///abacelor^abac
        ///abacul^abac
        ///abacului^abac
        ///abaca^abacă
        ///abace^abacă
        ///abacei^abacă
        ///abacele^abacă
        ///abacelor^abacă
        ///abagiţa^abagiţă
        ///abagiţe^abagiţă
        ///abagiţei^abagiţă
        ///abagiţele^abagiţă
        ///abagiţelor^abagiţă
        ///abagii^abagiu
        ///abagiii^abagiu
        ///abagiilor^abagiu
        ///abagiul^abagiu
        ///abagiului^abagiu
        ///abajurul^abajur
        ///abajurului^abajur
        ///abajururi^abajur
        ///abajururile^abajur
        ///abajururilor^abajur
        ///abandonul^abandon
        ///abandonulu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_ro {
            get {
                return ResourceManager.GetString("manual_lemmatization_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abakuse^abakus
        ///abakusmi^abakus
        ///abakusoch^abakus
        ///abakusom^abakus
        ///abakusov^abakus
        ///abakusu^abakus
        ///abakusy^abakus
        ///abatíš^abatiša
        ///abatišami^abatiša
        ///abatiše^abatiša
        ///abatiši^abatiša
        ///abatišiach^abatiša
        ///abatišiam^abatiša
        ///abatišou^abatiša
        ///abatišu^abatiša
        ///abažúre^abažúr
        ///abažúrmi^abažúr
        ///abažúroch^abažúr
        ///abažúrom^abažúr
        ///abažúrov^abažúr
        ///abažúru^abažúr
        ///abažúry^abažúr
        ///abbéami^abbé
        ///abbého^abbé
        ///abbém^abbé
        ///abbému^abbé
        ///abbéoch^abbé
        ///abbéom^abbé
        ///abbéov^abbé
        ///abbéovia^abbé
        ///Abcházca^Abcházec
        ///Abcházcam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_sk {
            get {
                return ResourceManager.GetString("manual_lemmatization_sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to niti^!niti
        ///predstavitelji^!predstavitelj
        ///Aaronsona^Aaronson
        ///Aaronsone^Aaronson
        ///Aaronsoni^Aaronson
        ///Aaronsonih^Aaronson
        ///Aaronsonom^Aaronson
        ///Aaronsonoma^Aaronson
        ///Aaronsonov^Aaronson
        ///Aaronsonu^Aaronson
        ///Abanki^Abanka
        ///Abebi^Abeba
        ///abecedi^abeceda
        ///abecednem^abeceden
        ///abecedni^abeceden
        ///abecednika^abecednik
        ///abecednike^abecednik
        ///abecedniki^abecednik
        ///abecednikih^abecednik
        ///abecednikom^abecednik
        ///abecednikoma^abecednik
        ///abecednikov^abecednik
        ///abecedniku^abecednik
        ///Abela^Abel
        ///Abrahamom^Abraham
        ///absolutn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_sl {
            get {
                return ResourceManager.GetString("manual_lemmatization_sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A:et^A
        ///a:ets^a
        ///A:n^A
        ///a:na^a
        ///A:nas^A
        ///a:ns^a
        ///a:s^a
        ///A:t^A
        ///a:ts^a
        ///a-et^a
        ///A-ets^A
        ///A-n^A
        ///A-na^A
        ///a-nas^a
        ///A-ns^A
        ///a-s^a
        ///A-t^A
        ///a-ts^a
        ///ä:et^ä
        ///ä:ets^ä
        ///ä:n^ä
        ///ä:na^ä
        ///ä:nas^ä
        ///ä:ns^ä
        ///ä:s^ä
        ///ä:t^ä
        ///ä:ts^ä
        ///ä-et^ä
        ///ä-ets^ä
        ///ä-n^ä
        ///ä-na^ä
        ///ä-nas^ä
        ///ä-ns^ä
        ///ä-s^ä
        ///ä-t^ä
        ///ä-ts^ä
        ///å:et^å
        ///å:ets^å
        ///å:n^å
        ///å:na^å
        ///å:nas^å
        ///å:ns^å
        ///å:s^å
        ///å:t^å
        ///å:ts^å
        ///åar^å
        ///åarna^å
        ///åarnas^å
        ///åars^å
        ///å-et^å
        ///å-ets^å
        ///ån^å
        ///å-n^å
        ///å-na^å
        ///å-nas^å
        ///åns^å
        ///å-ns^å
        ///ås^å
        ///å-s^å
        ///å-t^å
        ///å-ts^å
        ///A3:s^A3
        ///a3s^a3
        ///a3-s^a3
        ///A4:s^A4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_sv {
            get {
                return ResourceManager.GetString("manual_lemmatization_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to абзаца^абзац
        ///абзацам^абзац
        ///абзацами^абзац
        ///абзацах^абзац
        ///абзаце^абзац
        ///абзаци^абзац
        ///абзаці^абзац
        ///абзаців^абзац
        ///абзацові^абзац
        ///абзацом^абзац
        ///абзацу^абзац
        ///абонента^абонент
        ///абонентам^абонент
        ///абонентами^абонент
        ///абонентах^абонент
        ///абоненте^абонент
        ///абоненти^абонент
        ///абоненті^абонент
        ///абонентів^абонент
        ///абонентові^абонент
        ///абонентом^абонент
        ///абоненту^абонент
        ///абсолютна^абсолютний
        ///абсолютная^абсолютний
        ///абсолютне^абсолютний
        ///абсолютнеє^абсолютний
        ///абсолютним^абсолютний
        ///абсолютними^абсолютний
        ///абсолют [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_uk {
            get {
                return ResourceManager.GetString("manual_lemmatization_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MEHSplash {
            get {
                object obj = ResourceManager.GetObject("MEHSplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon mehv2 {
            get {
                object obj = ResourceManager.GetObject("mehv2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و
        ///در
        ///به
        ///از
        ///كه
        ///مي
        ///اين
        ///است
        ///را
        ///با
        ///هاي
        ///براي
        ///آن
        ///يك
        ///شود
        ///شده
        ///خود
        ///ها
        ///كرد
        ///شد
        ///اي
        ///تا
        ///كند
        ///بر
        ///بود
        ///گفت
        ///نيز
        ///وي
        ///هم
        ///كنند
        ///دارد
        ///ما
        ///كرده
        ///يا
        ///اما
        ///بايد
        ///دو
        ///اند
        ///هر
        ///خواهد
        ///او
        ///مورد
        ///آنها
        ///باشد
        ///ديگر
        ///مردم
        ///نمي
        ///بين
        ///پيش
        ///پس
        ///اگر
        ///همه
        ///صورت
        ///يكي
        ///هستند
        ///بي
        ///من
        ///دهد
        ///هزار
        ///نيست
        ///استفاده
        ///داد
        ///داشته
        ///راه
        ///داشت
        ///چه
        ///همچنين
        ///كردند
        ///داده
        ///بوده
        ///دارند
        ///همين
        ///ميليون
        ///سوي
        ///شوند
        ///بيشتر
        ///بسيار
        ///روي
        ///گرفته
        ///هايي
        ///تواند
        ///اول
        ///نام
        ///هيچ
        ///چند
        ///جديد
        ///بيش
        ///شدن
        ///كردن
        ///كنيم
        ///نشان
        ///حتي
        ///اينكه
        ///ولی
        ///توسط
        ///چنين
        ///برخي [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string persianST {
            get {
                return ResourceManager.GetString("persianST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ach
        ///aj
        ///albo
        ///bardzo
        ///bez
        ///bo
        ///być
        ///ci
        ///cię
        ///ciebie
        ///co
        ///czy
        ///daleko
        ///dla
        ///dlaczego
        ///dlatego
        ///do
        ///dobrze
        ///dokąd
        ///dość
        ///dużo
        ///dwa
        ///dwaj
        ///dwie
        ///dwoje
        ///dziś
        ///dzisiaj
        ///gdyby
        ///gdzie
        ///go
        ///ich
        ///ile
        ///im
        ///inny
        ///ja
        ///ją
        ///jak
        ///jakby
        ///jaki
        ///je
        ///jeden
        ///jedna
        ///jedno
        ///jego
        ///jej
        ///jemu
        ///jeśli
        ///jest
        ///jestem
        ///jeżeli
        ///już
        ///każdy
        ///kiedy
        ///kierunku
        ///kto
        ///ku
        ///lub
        ///ma
        ///mają
        ///mam
        ///mi
        ///mną
        ///mnie
        ///moi
        ///mój
        ///moja
        ///moje
        ///może
        ///mu
        ///my
        ///na
        ///nam
        ///nami
        ///nas
        ///nasi
        ///nasz
        ///nasza
        ///nasze
        ///natychmiast
        ///nią
        ///nic
        ///nich
        ///nie
        ///niego
        ///niej
        ///niemu
        ///nig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string polishST {
            get {
                return ResourceManager.GetString("polishST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а
        ///е
        ///и
        ///ж
        ///м
        ///о
        ///на
        ///не
        ///ни
        ///об
        ///но
        ///он
        ///мне
        ///мои
        ///мож
        ///она
        ///они
        ///оно
        ///мной
        ///много
        ///многочисленное
        ///многочисленная
        ///многочисленные
        ///многочисленный
        ///мною
        ///мой
        ///мог
        ///могут
        ///можно
        ///может
        ///можхо
        ///мор
        ///моя
        ///моё
        ///мочь
        ///над
        ///нее
        ///оба
        ///нам
        ///нем
        ///нами
        ///ними
        ///мимо
        ///немного
        ///одной
        ///одного
        ///менее
        ///однажды
        ///однако
        ///меня
        ///нему
        ///меньше
        ///ней
        ///наверху
        ///него
        ///ниже
        ///мало
        ///надо
        ///один
        ///одиннадцать
        ///одиннадцатый
        ///назад
        ///наиболее
        ///недавно
        ///миллионов
        ///недалеко
        ///между
        ///низко
        ///меля
        ///нельзя
        ///нибудь
        ///непрерывно
        ///наконец
        ///никогда
        ///ник [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string russianstoplist {
            get {
                return ResourceManager.GetString("russianstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///acá
        ///acaba
        ///acabar
        ///acabo
        ///acerca
        ///acuerdo
        ///actualmente
        ///adelante
        ///además
        ///ademas
        ///agradecería
        ///ahí
        ///ahí
        ///ahora
        ///ahorita
        ///al
        ///ala
        ///algo
        ///alguien
        ///algun
        ///algún
        ///alguna
        ///alguna
        ///algunas
        ///algunas
        ///alguno
        ///alguno
        ///algunos
        ///algunos
        ///allá
        ///allí
        ///alrededor
        ///ambos
        ///ampliamos
        ///angie
        ///ante
        ///antes
        ///aparte
        ///apenas
        ///aquel
        ///aquellas
        ///aquellos
        ///aquí
        ///arriba
        ///así
        ///asi
        ///asunto
        ///atrás
        ///aun
        ///aún
        ///aunque
        ///aveces
        ///b
        ///baja
        ///bajo
        ///bastante
        ///bien
        ///buen
        ///buscar
        ///busco
        ///c
        ///cabe
        ///cada
        ///cada
        ///caer
        ///capaz
        ///capacidad
        ///casi
        ///caso
        ///cau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spanishstoplist {
            get {
                return ResourceManager.GetString("spanishstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///À
        ///AAH
        ///ABLE
        ///ABOUT
        ///ABOVE
        ///ABST
        ///ACCORDANCE
        ///ACCORDING
        ///ACCORDINGLY
        ///ACROSS
        ///ACT
        ///ACTUAL
        ///ACTUALLY
        ///ADDED
        ///ADIEU
        ///ADIOS
        ///ADJ
        ///AFTER
        ///AFTERWARDS
        ///AGAIN
        ///AGAINST
        ///AGO
        ///AH
        ///do+not
        ///be+not
        ///AHA
        ///AHEAD
        ///AHEM
        ///AHOY
        ///AIN&apos;T
        ///ALACK
        ///ALAS
        ///ALBEIT
        ///ALL
        ///ALLELUIA
        ///ALMOST
        ///ALOFT
        ///ALONG
        ///ALONGSIDE
        ///alot
        ///ALREADY
        ///ALSO
        ///ALTHO
        ///ALTHOUGH
        ///ALWAYS
        ///AM
        ///AMEN
        ///AMID
        ///AMIDST
        ///AMONG
        ///AMONGST
        ///AN
        ///AND
        ///ANOTHER
        ///ANTI
        ///ANY
        ///ANYBODY
        ///ANYHOW
        ///ANYMORE
        ///ANYONE
        ///ANYPLACE
        ///ANYTHING
        ///ANYTIME
        ///ANYWAY
        ///ANYWAYS
        ///ANYWHERE
        ///ANYWISE
        ///APART
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stoplist_english {
            get {
                return ResourceManager.GetString("stoplist_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///able
        ///about
        ///above
        ///according
        ///accordingly
        ///across
        ///actually
        ///after
        ///afterwards
        ///again
        ///against
        ///all
        ///allow
        ///allows
        ///almost
        ///alone
        ///along
        ///already
        ///also
        ///although
        ///always
        ///am
        ///among
        ///amongst
        ///an
        ///and
        ///another
        ///any
        ///anybody
        ///anyhow
        ///anyone
        ///anything
        ///anyway
        ///anyways
        ///anywhere
        ///apart
        ///appear
        ///appreciate
        ///appropriate
        ///are
        ///around
        ///as
        ///aside
        ///ask
        ///asking
        ///associated
        ///at
        ///available
        ///away
        ///awfully
        ///b
        ///be
        ///became
        ///because
        ///become
        ///becomes
        ///becoming
        ///been
        ///before
        ///beforehand
        ///behind
        ///being
        ///believe
        ///below
        ///besid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stoplist_mallet_en {
            get {
                return ResourceManager.GetString("stoplist_mallet_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `
        ///~
        ///!
        ///@
        ///#
        ///$
        ///%
        ///^
        ///&amp;
        ///*
        ///(
        ///)
        ///_
        ///+
        ///-
        ///=
        ///[
        ///]
        ///\
        ///;
        ///&apos;
        ///,
        ///.
        ////
        ///{
        ///}
        ///|
        ///:
        ///&quot;
        ///&lt;
        ///&gt;
        ///?
        ///..
        ///...
        ///«
        ///««
        ///»»
        ///“
        ///”
        ///‘
        ///‘‘
        ///’
        ///’’
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///0
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///19
        ///20
        ///25
        ///30
        ///33
        ///40
        ///50
        ///60
        ///66
        ///70
        ///75
        ///80
        ///90
        ///99
        ///100
        ///123
        ///1000
        ///10000
        ///12345
        ///100000
        ///1000000.
        /// </summary>
        internal static string StopListCharacters {
            get {
                return ResourceManager.GetString("StopListCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///abir
        ///acaba
        ///alt
        ///altı
        ///altmış
        ///ama
        ///amp
        ///ancak
        ///arada
        ///aslında
        ///aynı
        ///ayrıca
        ///az
        ///b
        ///b
        ///bakan
        ///bana
        ///başka
        ///bazı
        ///bazı
        ///belki
        ///ben
        ///benden
        ///beni
        ///benim
        ///beri
        ///beş
        ///bile
        ///bin
        ///bir
        ///biraz
        ///birçok
        ///biri
        ///birkaç
        ///birkez
        ///birşey
        ///birşeyi
        ///biz
        ///bizden
        ///bize
        ///bizi
        ///bizim
        ///böyle
        ///böyle 
        ///böylece
        ///boyunca
        ///bu
        ///buna
        ///bunda
        ///bundan
        ///bunlar
        ///bunları
        ///bunların
        ///bunu
        ///bunun
        ///burada
        ///büyük
        ///c
        ///c
        ///Co
        ///co
        ///çoğu
        ///cok
        ///çok
        ///coskununyeri
        ///çünkü
        ///d
        ///da
        ///daha
        ///dahi
        ///de
        ///defa
        ///değil
        ///değil
        ///diğer
        ///diğer
        ///diye
        ///doksan
        ///dokuz
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string turkishstoplist {
            get {
                return ResourceManager.GetString("turkishstoplist", resourceCulture);
            }
        }
    }
}
